project:
  type: website
  output-dir: docs

website:
  title: "ETC5523 Blog Assessment"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ETC5523-2024/assignment-3-creating-a-blog-Qiuyuan0055.git
format:
  html:
    theme: flatly
    css: styles.css



